== Getting started with Apiman

This article will help you to get up and running with *apiman*, an open-source API management and gateway offering.

=== Apiman overview

APIs are becoming pervasive in the modern enterprise. External facing APIs allow 3rd party access to your company's content and services, while the trend towards microservices 
results in loosely coupled services, connected by multiple internal APIs. Using an API gateway helps you to centralize the management of your APIs, providing support for common features such as security, qoutas, logging and caching.

http://www.apiman.io[Apiman] is open-source API management software that simplifies the control, distribution and monitoring of your APIs. It consists of two main components:

* An easy-to-use management interface that helps you to configure common policies for your APIs  
* A runtime gateway component that executes the rules defined in the configured policies 

=== Apiman features

The apiman software provides support for multiple policy rules that can be combined to achieve your desired outcome. It includes rules for:

* Securing access based on user identity (authentication), and based on user role (authorization)
* Limiting access using rate-limiting for fine-grained control, quotas for longer periods, and transfer qoutas for data-intensive operations
* Enabling/disabling access to subsets of an API
* Logging and caching 
* Enabling/disabling access from specific IP adresses


=== Advantages of apiman

In addition to the normal advantages of using open source software, apiman provides benefits in other ways. It has enterprise-grade security functionality, with a wide range of encryption, authentication, and authorization protocols supported. While the software provides many policies out-of-the-box, it is also extensible through the provision of a plug-in framework, allowing you to easily add support for the specific rules you require. In addition, all of the functionality provided by apiman in the manager UI is also accessible through a REST API, meaning you can easily automate common tasks.


== Installing the software

This article describes getting started with apiman version 1.5.7, using WildFly version 10.1 as the host application server. While the examples are shown running on Linux, the software also works on Windows.

=== Prerequisites

* *Java JDK 1.8 or newer:* You can use OpenJDK or Oracle's JDK. 
* *Git:* This is needed to download the quickstart sample used in this article.
* *Maven:* This is used to build the quickstart sample. Apache Maven 3.6.3 is the latest release and recommended version, but any version from 3.3 will work.

=== WildFly

WildFly is an application development platform, based on Jakarta EE. It is highly configurable, and facilitates faster development and testing.
It is an open source community project, sponsored by Red Hat(TM), and is available for use and distribution under the LGPL v2.1 license.

. Download the WildFly software from http://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.zip

. Extract the contents of the zip file

. Use the add-user script in the WildFy bin directory to configure a user, for example,
+
[source]
----
cd ~/wildfly-10.1.0.Final
./bin/add-user.sh -u user1 -p password1
----

If you are running Windows, you should use the ``add-user.bat`` or ``add-user.ps1`` script as appropriate.

=== Apiman

Download the apiman software from http://downloads.jboss.org/apiman/1.5.7.Final/apiman-distro-wildfly10-1.5.7.Final-overlay.zip

Extract the contents of the zip file

Copy the contents of the 

Establish that the overlay has worked correctly by checking the WildFly folder for the existence apiman configuration file:

[source]
----
$ ls ~/wildfly-10.1.0.Final/standalone/configuration/standalone-apiman.xml
---- 
 
=== Running the software

[source]
----
$ cd ~/
$ ./bin/standalone.sh -c standalone-apiman.xml
----


[source]
----
13:26:45,008 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
----


 
Server logs are available at ~/wildfly-10.1.0.Final/standalone/log/server.log


Log on to the server at http://127.0.0.1:9990 using the credentials you specified when running the add-user script.


Check that the apiman has been deployed correctly at http://127.0.0.1:9990/console/App.html#standalone-deployments


http://127.0.0.1:8080/apimanui

admin/admin123!



 
== Setup the quickstart sample API

=== Download the quickstart project

[source]
----
$ cd ~
$ git clone https://github.com/apiman/apiman-quickstarts.git

----

=== Build the sample API

[source]
----
$ cd apiman-quickstarts/echo-service
$ mvn package
$ ls ./target/apiman-quickstarts-echo-service-1.3.1.Final.war
----


=== Deploy the sample API

Copy the war file to the application server:

[source]
----
$ cp ~/apiman-quickstarts/echo-service/target/apiman-quickstarts-echo-service-1.3.1.Final.war ~/wildfly-10.1.0.Final/standalone/deployments/
----

=== Test the sample API

Use your browser to access the API at http://localhost:8080/apiman-echo. The service should return a response that is an copy (echo) of the request:

[source]
----
{
  "method" : "GET",
  "resource" : "/apiman-echo",
  "uri" : "/apiman-echo",
  "headers" : {
    "Accept" : "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "Upgrade-Insecure-Requests" : "1",
    "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36",
    "Connection" : "keep-alive",
    "Sec-Fetch-Dest" : "document",
    "Sec-Fetch-Site" : "none",
    "Host" : "localhost:8080",
    "Accept-Language" : "en-GB,en-US;q=0.9,en;q=0.8,de;q=0.7",
    "Accept-Encoding" : "gzip, deflate, br",
    "dnt" : "1",
    "Sec-Fetch-Mode" : "navigate"
  },
  "bodyLength" : null,
  "bodySha1" : null
}
----



== Configure an API producer

Now you have the sample API working, you can now use apiman to configure access to the API.

. Create an organization and add a plan containing a policy
. Configure an API specifying the target API implementation and plans to use



=== Create producer organization

Create a new organization to manage your APIs.   

[source]
----
http://127.0.0.1:8080/apimanui/api-manager/new-org
----

* *Organization Name:* ProducerOrg
* *Description:* A sample producer organization 

=== Create a new plan

Create a new plan within the specified organization: 

[source]
----
http://127.0.0.1:8080/apimanui/api-manager/new-plan
----

* *Organization:* ProducerOrg
* *Plan Name:* Gold
* *Initial Version:* 1.0 (default)
* *Description:* Most expensive plan

==== Add policy to plan

Adding a policy to a plan allows the policy's functionality to be applied to the API invocation as part of the overall policy chain.


http://127.0.0.1:8080/apimanui/api-manager/orgs/ProducerOrg/plans/Gold/1.0/new-policy

* *Policy Type:* Rate-limiting policy
+
--
.Rate Limiting Policy Configuration
* *# of requests:* 10
* *Granularity:* Client App
* *Duration:* Hour
--



==== Lock plan

You must lock a plan to make it available to be included in APIs. Locking a plan renders it immutable, requiring a new version to be created in order to make changes to the plan.

Click the Lock button and the plan status will change to Locked





=== Create API


[source]
----
http://127.0.0.1:8080/apimanui/api-manager/new-api
----

* *API Name:* echo
* *Initial Version:* 1.0 (default)
* *Description:* The echo service


==== Configure the API implementation

On the "Implementation" tab for the API, you configure the details of the real API being managed. 

[source]
----
http://127.0.0.1:8080/apimanui/api-manager/orgs/ProducerOrg/apis/echo/1.0/impl
----

* *API Endpoint:* http://localhost:8080/apiman-echo
* *API Type:* REST (default)
* *API Content Type:* JSON (default)
* *API Security:* None (default)


==== Configure the API plans

On the "Plans" tab, you configure which plans are available to a client application. If the API is marked as "Public", it can be invoked without sending an API Key. 

Choose the Gold plan that you created earlier and press "Save".


=== Publish the API

Click the Publish button to make the API available to consumers.





== Configure an API consumer


=== Create the consumer organization 

Create a new organization to consume the published API.   

[source]
----
http://127.0.0.1:8080/apimanui/api-manager/new-org
----

* *Organization Name:* ConsumerOrg
* *Description:* A sample consumer organization 


=== Create client application


Click the New Client Application button

http://127.0.0.1:8080/apimanui/api-manager/orgs/ConsumerOrg/clients


* *Organization:* ConsumerOrg
* *Client App Name:*  EchoApp
* *Initial Version:* 1.0 (default)
* *Description:* A client application for consuming the echo API


=== Create contract


. From the EchoApp page (http://127.0.0.1:8080/apimanui/api-manager/orgs/ConsumerOrg/clients/EchoApp/1.0), choose "Search for APIs to consume". If needed, you can use the search box to find the echo API.

. Click on the link to the echo service (or navigate directly to http://127.0.0.1:8080/apimanui/api-manager/browse/orgs/ProducerOrg/echo/1.0).

. Create a new contract for the Gold plan that you created earlier. After clicking on the "Create Contract" button on the Gold plan, you will be presented with 
a summary of the contract details:

** *Client App:* ConsumerOrg/EchoApp 1.0
** *Plan:* Gold
** *API:* ProducerOrg/echo 1.0

. Click "Create Contract" if you are happy with the details in the summary page.

. Click the "Register" button to register the application with the API Gateway, so that the gateway can act as a proxy for the API.



== Consume the API




http://127.0.0.1:8080/apimanui/api-manager/orgs/ConsumerOrg/clients/EchoApp/1.0/apis



https://localhost:8443/apiman-gateway/ProducerOrg/echo/1.0?apikey=591c4999-c9d7-4513-a395-79cd903309fc

[source]
----
{
  "method" : "GET",
  "resource" : "/apiman-echo",
  "uri" : "/apiman-echo",
  "headers" : {
    "Accept" : "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36",
    "Connection" : "keep-alive",
    "Sec-Fetch-Dest" : "document",
    "Sec-Fetch-Site" : "none",
    "Host" : "localhost:8080",
    "Accept-Encoding" : "gzip, deflate, br",
    "dnt" : "1",
    "Pragma" : "no-cache",
    "Sec-Fetch-Mode" : "navigate",
    "Cache-Control" : "no-cache",
    "Upgrade-Insecure-Requests" : "1",
    "Sec-Fetch-User" : "?1",
    "Accept-Language" : "en-GB,en-US;q=0.9,en;q=0.8,de;q=0.7"
  },
  "bodyLength" : null,
  "bodySha1" : null
}
----


[source]
----
{"type":"Other","failureCode":10005,"responseCode":429,"message":"Rate limit exceeded.",
 "headers":{"X-RateLimit-Limit":"10","X-RateLimit-Remaining":"-1","X-RateLimit-Reset":"3088"}}
----


== Summary



== Resources




Members - roles of 

API Developer
Client App Developer
Organization Owner



=== Add a second plan


* Create a plan named "Silver"
* Add a new policy to the plan with: 
** Policy type of rate limiting
** Policy configuration set to 5 requests per client app per day
* Lock the plan







