== Getting started with Apiman

This article will help you to get up and running with *apiman*, an open-source API management and gateway offering.

=== Apiman overview

APIs are becoming pervasive in the modern enterprise. External facing APIs allow 3rd party access to your company's content and services, while the trend towards microservices 
results in loosely coupled services, connected by multiple internal APIs. Using an API gateway helps you to centralize the management of your APIs, providing support for common features such as security, qoutas, logging and caching.

http://www.apiman.io[Apiman] is open-source API management software that simplifies the control, distribution and monitoring of your APIs. It consists of two main components:

* An easy-to-use management interface that helps you to define centralized policies for your APIs  
* A runtime gateway component that executes the rules defined in the configured policies 

=== Apiman features

The apiman software provides support for multiple policy rules that can be combined to achieve your desired ???. It includes rules for:

* Securing access based on user identity (authentication), and based on user role (authorization)
* Limiting access using rate-limiting for fine-grained control, quotas for longer periods, and transfer qoutas for data-intensive operations
* Enabling/disabling access to subsets of an API
* Logging and caching 
* Enabling/disabling access from specific IP adresses


=== Advantages of apiman

*Cost:* Using apiman, you will automatically gain from the benefits of using open source software. While cost effectiveness is an important factor when you are starting up,
it also matters if your APIs become very popular. In this scenario, not having to pay a 3rd party for your API management can make a big difference to your bottom line.

*Extensibility:* While the software provides support for many policies out of the box, it is also extensible through the provision of a plug-in framework.

*Security:* Apiman provides enterprise-grade security functionality, with a wide range of encryption, authentication, and authorization protocols supported.

*REST API:* All of the functionality provided by apiman in the manager UI is also accessible through a REST API. 
 


== Installing the software

This article describes getting started with apiman version 1.5.7, using WildFly version 10.1 as the host application server. While the examples are shown running on Linux, the software also works on Windows.

=== Prerequisites

* Java
* Git
* Maven

=== WildFly

WildFly is an application development platform, based on Jakarta EE. It is highly configurable, and facilitates faster development and testing.
It is an open source community project, sponsored by Red Hat(TM), and is available for use and distribution under the LGPL v2.1 license.

Download the WildFly software from http://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.zip

Extract the contents of the zip file

Configure a user


=== Apiman

Download the apiman software from http://downloads.jboss.org/apiman/1.5.7.Final/apiman-distro-wildfly10-1.5.7.Final-overlay.zip

Extract the contents of the zip file

Copy the contents of the 

Establish that the overlay has worked correctly by checking the WildFly folder for the existence apiman configuration file:

[source]
----
$ ls ~/wildfly-10.1.0.Final/standalone/configuration/standalone-apiman.xml
---- 
 
=== Running the software

[source]
----
$ cd ~/
$ ./bin/standalone.sh -c standalone-apiman.xml
----


[source]
----
13:26:45,008 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
----


 
Server logs are available at ~/wildfly-10.1.0.Final/standalone/log/server.log


Log on to the server at http://127.0.0.1:9990 using the credentials you specified when running the add-user script.


Check that the apiman has been deployed correctly at http://127.0.0.1:9990/console/App.html#standalone-deployments


http://127.0.0.1:8080/apimanui

admin/admin123!



 
== Setup the quickstart sample API

=== Download the quickstart project

[source]
----
$ cd ~
$ git clone https://github.com/apiman/apiman-quickstarts.git

----

=== Build the sample API

[source]
----
$ cd apiman-quickstarts/echo-service
$ mvn package
$ ls ./target/apiman-quickstarts-echo-service-1.3.1.Final.war
----


=== Deploy the sample API

Copy the war file to the application server:

[source]
----
$ cp ~/apiman-quickstarts/echo-service/target/apiman-quickstarts-echo-service-1.3.1.Final.war ~/wildfly-10.1.0.Final/standalone/deployments/
----

=== Test the sample API

Use your browser to access the API at http://localhost:8080/apiman-echo. The service should return a response that is an copy (echo) of the request:

[source]
----
{
  "method" : "GET",
  "resource" : "/apiman-echo",
  "uri" : "/apiman-echo",
  "headers" : {
    "Accept" : "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "Upgrade-Insecure-Requests" : "1",
    "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36",
    "Connection" : "keep-alive",
    "Sec-Fetch-Dest" : "document",
    "Sec-Fetch-Site" : "none",
    "Host" : "localhost:8080",
    "Accept-Language" : "en-GB,en-US;q=0.9,en;q=0.8,de;q=0.7",
    "Accept-Encoding" : "gzip, deflate, br",
    "dnt" : "1",
    "Sec-Fetch-Mode" : "navigate"
  },
  "bodyLength" : null,
  "bodySha1" : null
}
----



== Use apiman to configure the sample API 

Now you have the sample API working, you can now use apiman to configure access to the API.

=== Create new organization

Create a new Organization to manage your APIs and Client Apps.   

[source]
----
http://127.0.0.1:8080/apimanui/api-manager/new-org
----

* *Organization Name:* SampleOrg
* *Description:* A sample organization 

=== Create a new plan

Create a new plan within the specified organization: 

[source]
----
http://127.0.0.1:8080/apimanui/api-manager/new-plan
----

* *Organization:* SampleOrg
* *Plan Name:* Gold
* *Initial Version:* Default is 1.0
* *Description:* A sample organization

=== Add policy to plan

Adding a policy to a plan allows the policy's functionality to be applied to the API invocation as part of the overall policy chain.


http://127.0.0.1:8080/apimanui/api-manager/orgs/SampleOrg/plans/Gold/1.0/new-policy

* *Policy Type:* Rate-limiting policy
+
--
.Rate Limiting Policy Configuration
* *# of requests:* 10
* *Granularity:* Client App
--



=== Lock plan

You must lock a plan to make it available to be included in APIs. Locking a plan renders it immutable, requiring a new version to be created in order to make changes to the plan.

Click the Lock button and the plan status will change to Locked


=== Add a second plan


* Create a plan named "Silver"
* Add a new policy to the plan with: 
** Policy type of rate limiting
** Policy configuration set to 5 requests per client app per day
* Lock the plan


=== Create API


[source]
----
http://127.0.0.1:8080/apimanui/api-manager/new-api
----

* *API Name:* echo
* *Initial Version:* - default is 1.0
* *Description:* The echo service



The 'Implementation' tab is where you go to configure the details of the real API being managed. This is where you tell apiman where the API is, so that we can actually invoke it at runtime.

[source]
----
http://127.0.0.1:8080/apimanui/api-manager/orgs/SampleOrg/apis/echo/1.0/impl
----



The 'Plans' tab is used to configure which Plans (already defined in the Organization) are available when a Client App wishes to create an API Contract with this API. Optionally, an API can also be marked as "Public", which means that no API Contract is required (the API can be invoked without sending an API Key).




== Resources




Members - roles of 

API Developer
Client App Developer
Organization Owner











